### Register
@baseUrl = http://localhost:8000

POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "Trần Văn Đạt",
    "phone": "0121211212",
    "email": "tranvandatevondev0503+1@gmail.com",
    "password": "123123Scss"
}
###
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "tranvandatevondev0503@gmail.com",
    "password": "123123Scss"
}
###
GET {{baseUrl}}/auth/1 HTTP/1.1